# Generated by Django 3.1.6 on 2021-03-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0003_auto_20210317_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='homefields',
            name='spanheading',
            field=models.CharField(default='Get Into', max_length=100),
            preserve_default=False,
        ),
    ]
