# Generated by Django 3.1.6 on 2021-03-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0005_homefields_div2'),
    ]

    operations = [
        migrations.AddField(
            model_name='homefields',
            name='div2box1',
            field=models.ImageField(default=False, upload_to='media'),
        ),
    ]
