# Generated by Django 3.1.6 on 2021-03-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0006_homefields_div2box1'),
    ]

    operations = [
        migrations.AddField(
            model_name='homefields',
            name='div2box2',
            field=models.ImageField(default=False, upload_to='media'),
        ),
        migrations.AddField(
            model_name='homefields',
            name='div2box3',
            field=models.ImageField(default=False, upload_to='media'),
        ),
        migrations.AddField(
            model_name='homefields',
            name='div2box4',
            field=models.ImageField(default=False, upload_to='media'),
        ),
    ]
